# Generated by Django 2.0.6 on 2018-06-17 04:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BHK',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=100)),
                ('addhar', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='ClientReivew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.IntegerField(blank=True, null=True)),
                ('comment', models.CharField(blank=True, max_length=200, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Furnish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fully', models.IntegerField(blank=True, default=0, null=True)),
                ('partially', models.IntegerField(blank=True, default=0, null=True)),
                ('unfurnished', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OwnerInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('owner_password', models.CharField(max_length=200)),
                ('owner_mobile', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family', models.IntegerField(blank=True, default=0, null=True)),
                ('girls', models.IntegerField(blank=True, default=0, null=True)),
                ('bachelor', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('location', models.CharField(max_length=1000)),
                ('status', models.IntegerField(blank=True, default=1, null=True)),
                ('rating', models.IntegerField(blank=True, default=5, null=True)),
                ('created_at', models.DateField(blank=True, null=True)),
                ('budget', models.CharField(blank=True, max_length=500, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('apartment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='search.Apartment')),
                ('bhk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='search.BHK')),
                ('furnish', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='search.Furnish')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='search.Images')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.OwnerInfo')),
                ('preference', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='search.Preference')),
            ],
        ),
        migrations.AddField(
            model_name='clientreivew',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.OwnerInfo'),
        ),
    ]
